feeds:
  - https://www.bleepingcomputer.com/feed/
  - https://www.securitymagazine.com/rss/15
  - https://packetstorm.news/rss/news
  - https://hnrss.org/frontpage
  - https://cybersecuritynews.com/feed/
  # - https://www.cert.europa.eu/publications/security-advisories-rss
  # - https://api.msrc.microsoft.com/update-guide/rss
  - https://feeds.feedburner.com/TheHackersNews


topics:
  # Malware & Exploits
  - Ransomware
  - Zero-Day
  - Botnets

  # Supply Chain & Dev Security
  - Supply Chain Attacks
  - Dev Tool Risks

  # Enterprise Security
  - Microsoft, SAP, OpenText, Palo Alto, Cisco Vulnerabilities

  # Authentication Attacks
  - AiTM Attacks

  # Phishing & Social Engineering
  - Phishing
  - Social Engineering

  # Cloud & API Security
  - Cloud Vulnerabilities

  # Critical Infrastructure
  - Digital Infrastructure
  - Critical Infrastructure
  - IoT & OT Risks

  # AI & Emerging Tech
  - AI in Security
  - Deepfake Attacks

  # Social Media & Communication
  - Social Media Security

  # Data & Network Security
  - Data Breaches


excluded_topics:
  - Security Product Marketing
  - Conferences & Events
  - Success Stories
  - Training & Certifications
  - Bug Bounties
  - Blogs & Opinions
  - Cryptocurrency


data_period:
  # today
  # this_week
  # range:
  #   startDate: 2025-03-01
  #   endDate: 2025-03-03
  previous_week

email_notifications:
  enabled: false
  subscribers:
    - "roman.tolstosheyev.std@bhos.edu.az"
  cron: "21 17 * * 3"

max_articles: 20
ai_model: "deepseek-r1-distill-llama-70b"
refresh_rate_minutes: 1440 # 24 hours
request_rate_mseconds: 100
