feeds:
  - https://www.bleepingcomputer.com/feed/
  - https://www.securitymagazine.com/rss/15
  - https://packetstorm.news/rss/news
  - https://hnrss.org/frontpage


topics:
  - Ransomware Attacks
  - Zero-Day Exploit
  - Software Supply Chain Attack
  - Botnet Attack
  - Microsoft Products Vulnerability
  - Password Spraying
  - VS Code Extensions Security
  - Developer Tool Risks
  - Phishing attacks

data_period:
#  today
#  this_week
  range:
    startDate: 2025-03-07
    endDate: 2025-03-14

max_articles: 20
