feeds:
  - https://www.bleepingcomputer.com/feed/
  - https://www.securitymagazine.com/rss/15
  - https://packetstorm.news/rss/news
  - https://hnrss.org/frontpage
  - https://cybersecuritynews.com/feed/
  - https://www.cert.europa.eu/publications/security-advisories-rss
  - https://api.msrc.microsoft.com/update-guide/rss
  - https://feeds.feedburner.com/TheHackersNews


topics:
  # Malware and Exploits
  - Ransomware Attacks
  - Zero-Day Exploits
  - Botnet Attacks

  # Supply Chain and Developer Security
  - Software Supply Chain Attacks
  - Developer Tool Risks

  # Enterprise & Infrastructure Security
  - Microsoft Products, SAP, OpenText, Palo Alto, Cisco Security

  # Authentication & Access Attacks
  - Adversary-in-the-Middle (AiTM) Attacks

  # Phishing and Social Engineering
  - Phishing and Social Engineering Attacks

  # Cloud and API Security
  - Cloud Security Vulnerabilities

  # Digital and Critical Infrastructure Security
  - Digital Infrastructure Threats
  - Critical Infrastructure Attacks
  - IoT & OT Security Risks

  # Emerging Technologies and AI Risks
  - Artificial Intelligence in Cybersecurity
  - Deepfake and Synthetic Media Attacks

  # Social Media and Communication Risks
  - Social Media and Messengers Security

  # Data & Network Security
  - Data Breaches


data_period:
#  today
  # this_week
  range:
    startDate: 2025-03-10
    endDate: 2025-03-16

max_articles: 20
ai_model: "gemma2-9b-it"
