feeds:
  - https://www.bleepingcomputer.com/feed/
  - https://www.securitymagazine.com/rss/15
  - https://packetstorm.news/rss/news
  - https://www.cshub.com/rss/categories/attacks
  - https://www.cshub.com/rss/categories/cloud
  - https://www.cshub.com/rss/categories/data
  - https://www.cshub.com/rss/categories/malware
  - https://hnrss.org/frontpage
  - https://www.stackhawk.com/feed.xml


topics:
  - Ransomware Attacks
  - Zero-Day Exploit
  - Software Supply Chain Attack
  - Botnet Attack
  - Microsoft Products Vulnerability
  - Password Spraying
  - VS Code Extensions Security
  - Developer Tool Risks
