feeds:
  - https://www.bleepingcomputer.com/feed/
  - https://packetstorm.news/rss/news

topics:
  - Ransomware Attacks
  - Zero-Day Exploit
  - Software Supply Chain Attack
  - Botnet Attack
  - Microsoft Products Vulnerability
  - Password Spraying
  - VS Code Extensions Security
  - Developer Tool Risks
