name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0

      - name: Define Image Tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "TAG=latest" >> "$GITHUB_OUTPUT"
          else
            echo "TAG=stable" >> "$GITHUB_OUTPUT"
          fi

      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=${{ steps.set-tag.outputs.TAG }}

      - name: Build and Publish Image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

