name: Deploy to Environment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up bun CLI
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Determine Webhook
        id: set-webhook
        run: |
          echo "Branch ref: ${{ github.event.workflow_run.head_branch }}"
          if [[ "${{ github.event.workflow_run.head_branch }}" == "develop" ]]; then
            echo "WEBHOOK_URL=${{ secrets.RENDER_WEBHOOK_DEPLOY_TEST }}" >> "$GITHUB_OUTPUT"
          else
            echo "WEBHOOK_URL=${{ secrets.RENDER_WEBHOOK_DEPLOY }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Trigger Deployment Webhook
        run: |
          curl ${{ steps.set-webhook.outputs.WEBHOOK_URL }}
